version: "3.8"

services:
  webserver:
    build:
      context: ./nginx
    container_name: webserver
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=ghettohustler.com
      - NGINX_PORT=80

  client:
    build:
      context: ./client
    env_file: ./client/.env
    container_name: client
    stdin_open: true
    restart: unless-stopped
    depends_on:
      - webserver
    ports:
      - 3000:3000
    networks:
      - network
    volumes:
      - ./client:/usr/app
      - //usr/app/node-modules

  server:
    build:
      context: ./server
    env_file: ./server/.env
    networks:
      - network
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/usr/app/server
      - /usr/app/server/node-modules

  postgres:
    image: postgres:13.3-alpine
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - network

  redis:
    image: redis:6.2.4-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
